package main

import (
	"context"
	"fmt"
	"maps"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/ipy/jenny/internal/agent"
	"github.com/ipy/jenny/internal/api/router"
	"github.com/ipy/jenny/internal/clean"
	"github.com/ipy/jenny/internal/cli"
	"github.com/ipy/jenny/internal/compact"
	"github.com/ipy/jenny/internal/config"
	"github.com/ipy/jenny/internal/constants"
	"github.com/ipy/jenny/internal/git"
	"github.com/ipy/jenny/internal/log"
	"github.com/ipy/jenny/internal/mcp"
	"github.com/ipy/jenny/internal/memdir"
	"github.com/ipy/jenny/internal/plugin"
	"github.com/ipy/jenny/internal/redact"
	"github.com/ipy/jenny/internal/session"
	"github.com/ipy/jenny/internal/skills"
	"github.com/ipy/jenny/internal/tool"
	"github.com/joho/godotenv"
)

// AC4: --version and the stream-json claude_code_version field must agree.
// `version` defaults to constants.Version. To override at build time use
// `-ldflags '-X main.version=<value>'`.
var version = constants.Version

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

// loadEnvFiles reads .env and .jenny/.env from cwd (whichever exist) and
// applies them to the process environment. godotenv's default Load does NOT
// overwrite variables already set in the environment, so explicit `export`
// in the shell always wins. Missing files are not an error.
func loadEnvFiles(cwd string) {
	if cwd == "" {
		return
	}
	candidates := []string{
		filepath.Join(cwd, ".env"),
		filepath.Join(constants.ProjectJennyDir(cwd), ".env"),
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err != nil {
			continue
		}
		// Best-effort: errors are ignored — a malformed .env should not
		// prevent jenny from starting.
		_ = godotenv.Load(p)
	}
}

// shouldLaunchPortal returns true only when the explicit "portal" subcommand is provided.
// Note: macOS double-clicking a bare executable ALWAYS opens Terminal. This is a macOS
// limitation - there is no mechanism to suppress Terminal for bare Mach-O binaries.
// Users who want no-Terminal launch must use the optional .app bundle
// (generated by scripts/make-portal-app.sh).
func shouldLaunchPortal() bool {
	return len(os.Args) >= 2 && os.Args[1] == "portal"
}

// shouldRunClean returns true when `jenny clean [args]` is the invocation.
// Mirrors shouldLaunchPortal() so the housekeeping subcommands short-circuit
// the normal flag parsing path entirely.
func shouldRunClean() bool {
	return len(os.Args) >= 2 && os.Args[1] == "clean"
}

// shouldRunCompact returns true when `jenny compact [args]` is the invocation.
func shouldRunCompact() bool {
	return len(os.Args) >= 2 && os.Args[1] == "compact"
}

// runClean dispatches `jenny clean` and exits with the appropriate status code.
func runClean() int {
	dryRun, help, err := clean.ParseCleanArgs(os.Args[2:])
	if err != nil {
		fmt.Fprintf(os.Stderr, "jenny clean: %v\n", err)
		clean.RunCleanHelp(os.Stdout, os.Stderr)
		return 2
	}
	if help {
		return clean.RunCleanHelp(os.Stdout, os.Stderr)
	}
	return clean.RunClean(dryRun, os.Stdout, os.Stderr)
}

// runCompact dispatches `jenny compact [id] [--dry-run] [--force]` and exits
// with the appropriate status code.
func runCompact() int {
	id, dryRun, force, help, err := compact.ParseCompactArgs(os.Args[2:])
	if err != nil {
		fmt.Fprintf(os.Stderr, "jenny compact: %v\n", err)
		compact.RunCompactHelp(os.Stdout, os.Stderr)
		return 2
	}
	if help {
		return compact.RunCompactHelp(os.Stdout, os.Stderr)
	}
	return compact.RunCompact(id, dryRun, force, os.Stdout, os.Stderr)
}

func run() error {
	// Launch portal only when explicit "portal" subcommand is provided.
	// Note: macOS double-clicking a bare executable ALWAYS opens Terminal -
	// this is a macOS limitation, not a code bug.
	if shouldLaunchPortal() {
		return runPortal(context.Background())
	}

	// `jenny clean` and `jenny compact` short-circuit the normal flag path
	// because they have their own flag sets. They exit with their own status.
	if shouldRunClean() {
		os.Exit(runClean())
	}
	if shouldRunCompact() {
		os.Exit(runCompact())
	}

	// AC9: load .env files (and .jenny/.env) before parsing flags so any
	// env-driven flag behaviour or pre-flight checks see the merged env.
	// Best-effort: missing or malformed .env is not an error.
	if cwd, err := os.Getwd(); err == nil {
		loadEnvFiles(cwd)
	}

	// Parse command-line flags
	flags, k, err := cli.Parse()
	if err != nil {
		return err
	}

	// --version / -v: print the version and exit before any session,
	// API client, or MCP setup so no network call is made.
	if flags.Version {
		fmt.Printf("%s (jenny)\n", version)
		return nil
	}

	// Initialize the global model registry early so that config.json models
	// block validation (WARN on malformed) happens even for --print-system-prompt.
	// Cache is stored at ~/.jenny/models.json with metadata in ~/.jenny/meta.json.
	registryCachePath := filepath.Join(constants.JennyHomeDir(), "models.json")
	config.InitGlobalRegistry(registryCachePath)
	reg := config.GlobalRegistry()
	if reg == nil {
		log.Warn("registry: failed to initialize global registry")
	}

	// --offline: skip all network fetch
	if flags.Offline && reg != nil {
		reg.SetOffline(true)
		log.Debug("registry: offline mode enabled, using cache as-is")
	}
	// Load user model overrides from config.json. Do this early so diagnostics
	// (e.g. WARN on malformed models block) are emitted before any early exit.
	if reg != nil {
		cwd, err := os.Getwd()
		if err != nil {
			cwd = "/"
		}
		configPath := filepath.Join(constants.ProjectJennyDir(cwd), "config.json")
		if data, err := os.ReadFile(configPath); err == nil {
			if models, err := reg.ParseConfigModels(data); err == nil && models != nil {
				if err := reg.ApplyUserOverrides(models); err != nil {
					log.Warn("registry: failed to apply user overrides", "error", err)
				}
			}
		}
	}

	// --print-system-prompt: print the assembled system prompt and exit.
	if flags.PrintSystemPrompt {
		cwd, err := os.Getwd()
		if err != nil {
			cwd = "/"
		}
		tools := buildPrintTools(flags)
		cfg := agent.StreamConfig{
			CustomSystemPrompt:  flags.CustomSystemPrompt,
			PrependSystemPrompt: flags.PrependSystemPrompt,
			AppendSystemPrompt:  flags.AppendSystemPrompt,
			MemoryContent:       agent.LoadInstructionFile(cwd),
			MaxIterations:      flags.MaxIterations,
		}
		fmt.Print(agent.AssembleSystemPrompt(&cfg, tools, cwd))
		return nil
	}

	// Set verbose mode in the logger (re-runs resetLogger to enable debug level).
	// The JENNY_DEBUG env var is read by internal/log/log.go's init() and is
	// the canonical site; flags.Verbose here is the CLI-flag-driven override.
	log.SetVerbose(flags.Verbose)

	// --refresh-registry: synchronous fetch, blocking, errors surface.
	// When --offline is also set, skip the fetch with a clear warning since the
	// two flags are mutually exclusive (enforced by cli.Parse).
	if flags.RefreshRegistry && reg != nil {
		if flags.Offline {
			log.Warn("registry: --refresh-registry ignored because --offline is active")
		} else {
			if err := reg.Fetch(); err != nil {
				return fmt.Errorf("failed to refresh model registry: %w", err)
			}
			log.Info("registry: refreshed successfully")
		}
	}

	// If no --refresh-registry and not offline, start background fetch with 3s soft timeout.
	if reg != nil && !flags.RefreshRegistry && !flags.Offline && reg.ShouldFetch() {
		go func() {
			done := make(chan struct{})
			go func() {
				if err := reg.Fetch(); err != nil {
					log.Warn("registry: background fetch failed", "error", err)
				}
				close(done)
			}()
			select {
			case <-done:
				// fetch completed within timeout
			case <-time.After(3 * time.Second):
				log.Debug("registry: background fetch still running (soft timeout)")
			}
		}()
	}

	// Initialize the multi-provider router from config.json via koanf (or env).
	// Idempotent: subsequent calls are no-ops.
	routerCfg, err := router.LoadConfigFromKoanf(k)
	if err != nil {
		log.Warn("router config load failed", "err", err)
	}
	if err := router.Init(routerCfg); err != nil && err != router.ErrNoProviders {
		log.Warn("router initialization skipped", "err", err)
	}

	// Get working directory
	cwd, err := os.Getwd()
	if err != nil {
		cwd = "/"
	}

	// Create session manager for transcript persistence.
	// Transcript directory flows through the koanf config layer
	// (--transcript-dir / JENNY_TRANSCRIPT_DIR / .jenny/config.json).
	sessionManager, err := session.NewManager(flags.TranscriptDir, flags.NoSessionPersistence)
	if err != nil {
		return fmt.Errorf("creating session manager: %w", err)
	}

	// Register shutdown flush hook when persistence is enabled
	if !flags.NoSessionPersistence {
		sessionManager.RegisterShutdownFlush()
	}

	// Handle --continue flag: find most recent session
	if flags.Continue {
		sessions, err := sessionManager.ListSessions()
		if err != nil {
			return fmt.Errorf("listing sessions: %w", err)
		}
		if len(sessions) == 0 {
			return fmt.Errorf("no sessions to continue")
		}
		flags.SessionResume = sessions[0]
	}

	// Determine session ID: use -r flag value if provided, otherwise generate new
	sessionID := flags.SessionResume
	var historyMessages []agent.Message

	if sessionID == "" {
		sessionID, err = session.NewSessionID()
		if err != nil {
			return fmt.Errorf("generating session ID: %w", err)
		}
	} else {
		// When persistence is disabled, resume is not supported
		if flags.NoSessionPersistence {
			return fmt.Errorf("session persistence is disabled, cannot resume session %s", sessionID)
		}

		// Validate session ID doesn't contain path traversal before using it
		if err := session.ValidateSessionID(sessionID); err != nil {
			return err
		}

		// AC8: transparently rebuild the session directory from a sibling
		// <id>.tar.gz archive produced by `jenny compact` before checking
		// for existence. After this call the regular session lookup flow
		// runs against the freshly extracted directory. The keepArchive flag
		// flows through the koanf config layer
		// (--compact-keep-archive / JENNY_COMPACT_KEEP_ARCHIVE).
		if err := session.MaybeExtractArchive(sessionID, flags.CompactKeepArchive); err != nil {
			return fmt.Errorf("extracting compact archive for session %s: %w", sessionID, err)
		}

		// Check if the session exists when resuming
		if !sessionManager.SessionExists(sessionID) {
			return fmt.Errorf("session not found: %s", sessionID)
		}

		// Load transcript for validation (LoadPostBoundaryMessages for history)
		// Use LoadPostBoundaryMessages to skip pre-compaction messages when resuming
		entries, err := sessionManager.LoadPostBoundaryMessages(sessionID)
		if err != nil {
			return fmt.Errorf("loading transcript: %w", err)
		}

		// Reject queue-only/empty transcripts: if no chain participant messages
		// exist after filtering progress types, the session has no conversation to resume.
		if !agent.HasChainMessages(entries) {
			return fmt.Errorf("no conversation found in session %s", sessionID)
		}

		historyMessages = agent.RebuildMessages(entries)

		// Fork session if --fork-session flag is set
		if flags.ForkSession {
			newSessionID, err := session.NewSessionID()
			if err != nil {
				return fmt.Errorf("generating new session ID for fork: %w", err)
			}

			// Write all loaded entries to the new session
			for _, entry := range entries {
				if err := sessionManager.AppendEntry(newSessionID, entry); err != nil {
					return fmt.Errorf("forking transcript entry: %w", err)
				}
			}

			// Use the new session ID for the remainder of the run
			sessionID = newSessionID
		}
	}

	// Load MCP configuration
	var mcpConfig map[string]mcp.MCPServerDef
	var mcpTools []tool.Tool

	// Always add ListMcpResourcesTool - it handles the case of no MCP servers connected
	mcpTools = append(mcpTools, mcp.NewListMcpResourcesTool())

	// Phase 0: Auto-load default MCP configs (~/.agents/mcp.json, ~/.jenny/mcp.json)
	// if not bare and not strict. These are loaded automatically (no CLI flag required).
	if !flags.Bare && !flags.StrictMCP {
		defaultPaths := collectDefaultMCPPaths(cwd, constants.JennyHomeDir(), constants.AgentsHomeDir())
		if len(defaultPaths) > 0 {
			defaultConfig, err := mcp.LoadConfig(defaultPaths, false) // strict=false: merge, don't fail
			if err != nil {
				// Log but don't fail - default configs are optional
				fmt.Fprintf(os.Stderr, "warning: loading default MCP config: %v\n", err)
			} else if defaultConfig != nil {
				mcpConfig = defaultConfig
			}
		}
	}

	// Phase 1: Load plugin MCP servers (lowest priority) if not bare and not strict.
	// Merge into existing mcpConfig from Phase 0 (plugin wins on collision? No —
	// default configs have higher priority than plugin configs, so default wins).
	if !flags.Bare && !flags.StrictMCP {
		pluginConfig := loadPluginMCPServers(cwd, constants.JennyHomeDir(), constants.AgentsHomeDir())
		if mcpConfig == nil {
			mcpConfig = pluginConfig
		} else {
			// Plugin defs only fill gaps — default configs (Phase 0) win on collision
			for name, def := range pluginConfig {
				if _, exists := mcpConfig[name]; !exists {
					mcpConfig[name] = def
				}
			}
		}
	}

	// Phase 2: Merge CLI MCP config (overrides plugin entries)
	if len(flags.MCPConfig) > 0 {
		cliConfig, err := mcp.LoadConfig(flags.MCPConfig, flags.StrictMCP)
		if err != nil {
			return fmt.Errorf("loading MCP config: %w", err)
		}
		// Merge CLI config into plugin config (CLI wins on collision)
		if mcpConfig == nil {
			mcpConfig = cliConfig
		} else {
			maps.Copy(mcpConfig, cliConfig)
		}
	}

	// Phase 3: Connect and discover tools if we have any MCP servers
	if len(mcpConfig) > 0 {
		if err := mcp.ConnectAll(mcpConfig); err != nil {
			return fmt.Errorf("connecting to MCP servers: %w", err)
		}

		// Get discovered MCP tools
		for _, t := range mcp.GetTools() {
			if mcpTool, ok := t.(*mcp.MCPTool); ok {
				mcpTools = append(mcpTools, mcpTool)
			}
		}

		// Ensure MCP clients are shut down on exit
		defer mcp.ShutdownAll()
	}

	// Build tool registry
	// AC4: ReadFileCache is wired through StreamConfig -> QueryEngine -> tools
	// But Registry.Build() also needs it to create Write/Edit/NotebookEdit tools
	readFileCache := tool.NewReadFileCache()

	// Discover skills from project .jenny/skills/ directory and bundled default directory
	var discoveredSkills []skills.Skill
	var pluginInfo []cli.PluginInitInfo

	// AC4: Bare mode skips all skill discovery
	if !flags.Bare {
		// Project-level skills: .jenny/skills/ (highest) then .agents/skills/
		projectSkillsDir := filepath.Join(constants.ProjectJennyDir(cwd), "skills")
		projectAgentsDir := filepath.Join(cwd, constants.AgentsDirName, "skills")

		// User-level skills: .jenny/skills/ (higher) then .agents/skills/ (lowest)
		var userSkillsDirs []string
		if jennyHome := constants.JennyHomeDir(); jennyHome != "" {
			userSkillsDirs = append(userSkillsDirs, filepath.Join(jennyHome, "skills"))
		}
		if agentsHome := constants.AgentsHomeDir(); agentsHome != "" {
			userSkillsDirs = append(userSkillsDirs, filepath.Join(agentsHome, "skills"))
		}

		// Discover from all directories (AC6: discovery from multiple directories)
		// Priority (highest first): project/.jenny > project/.agents > ~/.jenny > ~/.agents
		discoveredSkills, err = skills.Discover(
			append([]string{projectSkillsDir, projectAgentsDir}, userSkillsDirs...)...,
		)
		if err != nil {
			return fmt.Errorf("discovering skills: %w", err)
		}

		// Discover plugin skills and merge with discovered skills
		// Plugin skills have lower priority than project/user skills (dedup by name)
		pluginRoots := plugin.FindPluginRoots(cwd)
		homePluginRoots := plugin.FindPluginRoots(constants.JennyHomeDir())
		pluginRoots = append(pluginRoots, homePluginRoots...)
		agentsPluginRoots := plugin.FindPluginRoots(constants.AgentsHomeDir())
		pluginRoots = append(pluginRoots, agentsPluginRoots...)

		discoveredSkills = discoverAndMergePluginSkills(discoveredSkills, pluginRoots)

		// Build plugin info for init event (dedup by name)
		seenPlugins := make(map[string]bool)
		for _, root := range pluginRoots {
			loaded := loadPluginFromRoot(root)
			if loaded == nil || seenPlugins[loaded.Manifest.Name] {
				continue
			}
			seenPlugins[loaded.Manifest.Name] = true
			pluginInfo = append(pluginInfo, cli.PluginInitInfo{
				Name:   loaded.Manifest.Name,
				Path:   root,
				Source: "project",
			})
		}
	}

	var tools []tool.Tool
	// Resolve permission level from --dangerously-skip-permissions and --permission-level flags.
	permLevel, permWarning := tool.ResolvePermissionLevel(flags.SkipPermissions, flags.PermissionLevel)
	if permWarning != "" {
		log.Warn(permWarning)
	}
	registry := tool.NewRegistry().
		WithBaseTools().
		WithWebFetchEnabled(true).
		WithWebSearchEnabled(true).
		WithReadFileCache(readFileCache).
		WithMCPTools(mcpTools).
		WithDenyRules(flags.DeniedTools).
		WithPermissionLevel(permLevel).
		WithStrictMCP(flags.StrictMCP).
		WithSkillsFrameworkEnabled(!flags.Bare, discoveredSkills)

	// Resolve web search configuration from koanf and wire client providers.
	searchCfg := tool.ResolveWebSearchConfig(k)
	if err := tool.ValidateWebSearchConfig(searchCfg); err != nil {
		log.Warn("web search config invalid, using defaults", "err", err)
		c := tool.DefaultWebSearchConfig()
		searchCfg = c
	}
	if searchCfg.Strategy == tool.StrategyClient || searchCfg.Strategy == tool.StrategyNative {
		if clientProvider, err := tool.NewSearchClientProvider(searchCfg.ClientConfig); err == nil {
			registry.WithSearchClientProvider(clientProvider)
		} else {
			log.Warn("web search client provider not created", "err", err)
		}
	}
	registry.WithWebSearchConfig(&searchCfg)

	tools = registry.Build()

	// Get skill activator to wire it to the engine for active skill tracking
	skillActivator := registry.GetSkillActivator()

	// Create subagent runners and AgentTool
	denyRulesMap := make(map[string]bool)
	for _, name := range flags.DeniedTools {
		denyRulesMap[name] = true
	}
	localRunner := agent.NewLocalSubagentRunner(tools, denyRulesMap, nil)
	asyncRunner := agent.NewAsyncSubagentRunner(tools, denyRulesMap, nil)
	agentTool := tool.NewAgentToolWithSwarms(localRunner, asyncRunner, flags.SwarmsEnabled)
	tools = append(tools, agentTool)

	// Create context that cancels on Ctrl+C (SIGINT) or SIGTERM
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	// Redact mode is read by the unified koanf config layer (cli.Flags.RedactMode):
	//   1. --redact CLI flag (highest)
	//   2. JENNY_REDACT env var / .jenny/config.json
	//   3. Default "redact" (one-way) when nothing is set, applied by ParseRedactMode.
	redactMode := redact.ParseRedactMode(flags.RedactMode)

	// Compact and auto-memory overrides flow from cli.Flags through StreamConfig
	// into the engine, which builds the CompactConfig and memdir.Config from there.
	// See docs/arch/koanf-config.md for the full env-var/CLI precedence rule.

	// Compute memory path for init event
	var memoryPaths map[string]string
	if projectRoot, err := git.GetRoot(cwd); err == nil {
		memoryPaths = map[string]string{"auto": memdir.MemoryPathFromProjectRoot(projectRoot)}
	}

	// Build stream config
	// AC4: Create ReadFileCache and pass it through StreamConfig for engine-level wiring
	streamCfg := agent.StreamConfig{
		Enabled:             flags.OutputFormat == "stream-json",
		Verbose:             flags.Verbose,
		IncludePartial:      flags.IncludePartialMessages,
		SessionID:           sessionID,
		SessionManager:      sessionManager,
		HistoryMessages:     historyMessages,
		IsResume:            flags.SessionResume != "", // True when resuming an existing session via -r
		MCPConfig:           mcpConfig,
		ReadFileCache:       readFileCache,
		Skills:              discoveredSkills,
		CustomSystemPrompt:   flags.CustomSystemPrompt,
		PrependSystemPrompt: flags.PrependSystemPrompt,
		AppendSystemPrompt:  flags.AppendSystemPrompt,
		MemoryContent:       agent.LoadInstructionFile(cwd),
		MaxIterations:       flags.MaxIterations,
		MaxTurns:            flags.MaxTurns,
		MaxBudgetUSD:        flags.MaxBudgetUsd,
		RedactMode:          redactMode,
		Effort:              flags.Effort,
		ThinkingBudget:      flags.ThinkingBudget,
		MaxToolConcurrency:  flags.MaxToolConcurrency,
		DisableCompact:      flags.DisableCompact,
		DisableAutoCompact:  flags.DisableAutoCompact,
		EnableSessionMemory: flags.EnableSessionMemory,
		DisableAutoMemory:   flags.DisableAutoMemory,
		Plugins:             pluginInfo,
		MemoryPaths:         memoryPaths,
		PermissionLevel:     permLevel,
	}

	// AC3-streamconfig-inheritance: Set parent config on runner for named agent inheritance
	localRunner.SetParentConfig(&streamCfg)
	asyncRunner.SetParentConfig(&streamCfg)

	// Subagent integration: wire parent session ID so subagent transcript/cost land in parent dir
	localRunner.SetParentSessionID(sessionID)
	asyncRunner.SetParentSessionID(sessionID)

	// Create engine before RunStream so subagents can access ParentEngine during execution.
	// This is needed for cost merge: subagent reads r.parentConfig.ParentEngine after it completes.
	engine, err := agent.NewQueryEngine(&streamCfg, tools, flags.Model, agent.WithSkillActivator(skillActivator), agent.WithCWD(cwd))
	if err != nil {
		return err
	}
	streamCfg.ParentEngine = engine

	// Run agent (will reuse the engine we just created since ParentEngine is set)
	engine, result, _, err := agent.RunStream(ctx, flags.Prompt, tools, cwd, &streamCfg, flags.Model, agent.WithSkillActivator(skillActivator))
	if err != nil {
		return err
	}

	// Print result only when NOT in stream-json mode (result is already emitted as JSON in stream-json mode)
	if flags.OutputFormat != "stream-json" {
		fmt.Println(result)
	}
	return nil
}

// buildPrintTools returns the default set of tools for system prompt printing.
// It skips MCP tool discovery and full skill discovery to remain offline.
func buildPrintTools(flags *cli.Flags) []tool.Tool {
	// Resolve permission level from --dangerously-skip-permissions and --permission-level flags.
	permLevel, _ := tool.ResolvePermissionLevel(flags.SkipPermissions, flags.PermissionLevel)
	registry := tool.NewRegistry().
		WithBaseTools().
		WithWebFetchEnabled(true).
		WithWebSearchEnabled(true).
		WithDenyRules(flags.DeniedTools).
		WithPermissionLevel(permLevel).
		WithStrictMCP(flags.StrictMCP).
		WithSkillsFrameworkEnabled(!flags.Bare, nil)
	tools := registry.Build()

	// Create subagent runners and AgentTool
	denyRulesMap := make(map[string]bool)
	for _, name := range flags.DeniedTools {
		denyRulesMap[name] = true
	}
	localRunner := agent.NewLocalSubagentRunner(tools, denyRulesMap, nil)
	asyncRunner := agent.NewAsyncSubagentRunner(tools, denyRulesMap, nil)
	agentTool := tool.NewAgentToolWithSwarms(localRunner, asyncRunner, flags.SwarmsEnabled)
	tools = append(tools, agentTool)

	return tools
}
